version: '3.7'

services:
  server:
   build: ./server
   command: python manage.py runserver 0.0.0.0:8101
   ports:
    - 8101:8101
  client:
    build: ./client/mlops-client
    ports:
    - 8201:8080
